### ISSUE TITLE
in `callers': uninitialized constant RubyVM::DebugInspector (NameError)

### ISSUE THREAD

**Issue by Lebanon** [JulianNicholls/complete-saas-app#2]
Hello Julian,

I'm trying to run the application using Mac and I'm getting an error (see log).  
I already did some search and some suggested the following two command (which I did) but I'm still getting the same error:

**$ gem uninstall debug_inspector
(project_root) $ bundle**

Can you help?

Regards,

Ahmad
# 

/Users/Ahmad/RubymineProjects/complete-saas-app-mysql/vendor/bundle/ruby/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers': uninitialized constant RubyVM::DebugInspector (NameError)
    from /Users/Ahmad/RubymineProjects/complete-saas-app-mysql/vendor/bundle/ruby/2.2.0/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in`block in class:Exception'
    from /Users/Ahmad/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require'
    from /Users/Ahmad/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in`block (2 levels) in require'
    from /Users/Ahmad/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
    from /Users/Ahmad/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in`block in require'
    from /Users/Ahmad/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
    from /Users/Ahmad/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in`require'
    from /Users/Ahmad/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
    from /Users/Ahmad/RubymineProjects/complete-saas-app-mysql/config/application.rb:7:in`<top (required)>'
    from /Users/Ahmad/RubymineProjects/complete-saas-app-mysql/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:78:in `require'
    from /Users/Ahmad/RubymineProjects/complete-saas-app-mysql/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:78:in`block in server'
    from /Users/Ahmad/RubymineProjects/complete-saas-app-mysql/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `tap'
    from /Users/Ahmad/RubymineProjects/complete-saas-app-mysql/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in`server'
    from /Users/Ahmad/RubymineProjects/complete-saas-app-mysql/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /Users/Ahmad/RubymineProjects/complete-saas-app-mysql/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in`<top (required)>'
    from /Users/Ahmad/RubymineProjects/complete-saas-app-mysql/bin/rails:9:in `require'
    from /Users/Ahmad/RubymineProjects/complete-saas-app-mysql/bin/rails:9:in`<top (required)>'
    from -e:1:in `load'
    from -e:1:in`<main>'

Process finished with exit code 1
#

**Comment by JulianNicholls** [comment]
Try doing

`bundle update`

and see if that improves it.

Otherwise you could remove the `better_errors` and `binding_of_caller` gems from the `Gemfile` and run `bundle` again.
